### ISSUE TITLE
Ava: All Smacks Page

### ISSUE THREAD

**Issue by avabrooks** [evagravin/p4-kangaroos#26]
- [x] Display data from db of all guest smacks
   - [x] Use for loop and jinja variables to filter by guests
   - [x] Pull from guest  table and display name, emotion, and update in viewable table

**Comment by evagravin** [comment]
I can see that this ticket is not as developed yet as your other one since you did two but displaying the data of the smacks will be really helpful. Maybe you can specify if jinja will be used to do this or something else. Also being able to search for posts would be really cool. We might be able to do that with a JavaScript feature (an idea).
